update openrc and sysvinit service templates

diff --git a/services/sysvinit/init.d/c8y-log-plugin b/services/sysvinit/init.d/c8y-log-plugin
--- a/services/sysvinit/init.d/c8y-log-plugin
+++ b/services/sysvinit/init.d/c8y-log-plugin
@@ -1,91 +1,192 @@
 #! /bin/sh
-
 ### BEGIN INIT INFO
-# Provides:		tedge-agent
-# Required-Start:	$remote_fs $syslog
-# Required-Stop:	$remote_fs $syslog
-# Default-Start:	2 3 4 5
-# Default-Stop:		0 1 6
-# Short-Description:	Thin-edge logfile retriever for Cumulocity
-# Description:
-#  Thin-edge logfile retriever for Cumulocity
+# Provides:          c8y-log-plugin
+# Required-Start:    $local_fs
+# Should-Start:
+# Required-Stop:     $local_fs
+# Should-Stop:
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Thin-edge logfile retriever for Cumulocity
+# Description:       Thin-edge logfile retriever for Cumulocity
 #
 ### END INIT INFO
 
-set -e
+# The definition of actions: (From LSB 3.1.0)
+# start         start the service
+# stop          stop the service
+# restart       stop and restart the service if the service is already running,
+#               otherwise start the service
+# try-restart	restart the service if the service is already running
+# reload	cause the configuration of the service to be reloaded without
+#               actually stopping and restarting the service
+# force-reload	cause the configuration to be reloaded if the service supports
+#               this, otherwise restart the service if it is running
+# status	print the current status of the service
 
-PIDFILE=/run/lock/c8y-log-plugin.pid
+# The start, stop, restart, force-reload, and status actions shall be supported
+# by all init scripts; the reload and the try-restart actions are optional
+
+# NOTE: The skeleton doesn't support the daemon which is a script unless the
+#       pidof supports "-x" option, please see more comments for pidofproc ()
+#       in /etc/init.d/functions
+
+# --- Custom ---
+# Skeleton: https://git.yoctoproject.org/poky/plain/meta-skeleton/recipes-skeleton/service/service/skeleton
+# shellcheck disable=SC2006
+# shellcheck disable=SC3043
+# shellcheck disable=SC1090
+# shellcheck disable=SC1091
+# --- End Custom ---
+
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+
+DESC="Thin-edge logfile retriever for Cumulocity"
 DAEMON=/usr/bin/c8y-log-plugin
-
 DAEMON_ARGS=""
+PIDFILE=/var/run/c8y-log-plugin.pid
 
-export TEDGE_RUN_LOCK_FILES="false"
+. /etc/init.d/functions || exit 1
 
-# /etc/init.d/c8y-log-plugin: start and stop c8y-log-plugin
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
 
-test -x ${DAEMON} || exit 0
+# Read configuration variable file if it is present
+[ -r /etc/default/c8y-log-plugin ] && . /etc/default/c8y-log-plugin
 
-umask 022
+#
+# Function that starts the daemon/service
+#
+do_start() {
+	local status pid
 
-. /lib/lsb/init-functions
+	status=0
+	pid=`pidofproc c8y-log-plugin` || status=$?
+	case $status in
+	0)
+		echo "$DESC already running ($pid)."
+		exit 1
+		;;
+	*)
+		echo "Starting $DESC ..."
+		exec $DAEMON $DAEMON_ARGS >/dev/null 2>&1 || status=$?
+		echo "ERROR: Failed to start $DESC."
+		exit $status
+		;;
+	esac
 
-# Are we running from init?
-run_by_init() {
-    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
+	# Add code here, if necessary, that waits for the process to be ready
+	# to handle requests from services started subsequently which depend
+	# on this one.  As a last resort, sleep for some time.
 }
 
-export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
+#
+# Function that stops the daemon/service
+#
+do_stop() {
+	local pid status
+
+	status=0
+	pid=`pidofproc c8y-log-plugin` || status=$?
+	case $status in
+	0)
+		# Exit when fail to stop, the kill would complain when fail
+		kill -s 15 $pid >/dev/null && rm -f $PIDFILE && \
+			echo "Stopped $DESC ($pid)." || exit $?
+		;;
+	*)
+		echo "$DESC is not running; none killed." >&2
+		;;
+	esac
+
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	return $status
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	local pid status
+
+	status=0
+        # If the daemon can reload its configuration without
+        # restarting (for example, when it is sent a SIGHUP),
+        # then implement that here.
+	pid=`pidofproc c8y-log-plugin` || status=$?
+	case $status in
+	0)
+		echo "Reloading $DESC ..."
+		kill -s 1 $pid || exit $?
+		;;
+	*)
+		echo "$DESC is not running; none reloaded." >&2
+		;;
+	esac
+	exit $status
+}
+
+
+#
+# Function that shows the daemon/service status
+#
+status_of_proc () {
+	local pid status
+
+	status=0
+	# pidof output null when no program is running, so no "2>/dev/null".
+	pid=`pidofproc c8y-log-plugin` || status=$?
+	case $status in
+	0)
+		echo "$DESC is running ($pid)."
+		exit 0
+		;;
+	*)
+		echo "$DESC is not running." >&2
+		exit $status
+		;;
+	esac
+}
 
 case "$1" in
-  start)
-	if init_is_upstart; then
-	    exit 1
-	fi
-	log_daemon_msg "Starting network daemon:" "c8y-log-plugin"
-	if start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile "${PIDFILE}" --exec "${DAEMON}" -- $DAEMON_ARGS ; then
-	    log_end_msg 0
-	else
-	    log_end_msg 1
-	fi
+start)
+	do_start
 	;;
-  stop)
-	if init_is_upstart; then
-	    exit 0
-	fi
-	log_daemon_msg "Stopping network daemon:" "c8y-log-plugin"
-	if start-stop-daemon --stop --quiet --oknodo --pidfile "${PIDFILE}"; then
-	    log_end_msg 0
-	    rm -f "${PIDFILE}"
-	else
-	    log_end_msg 1
-	fi
+stop)
+	do_stop || exit $?
 	;;
-
-  restart)
-	if init_is_upstart; then
-	    exit 1
-	fi
-	log_daemon_msg "Restarting network daemon:" "c8y-log-plugin"
-	if start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile "${PIDFILE}"; then
-	    rm -f "${PIDFILE}"
-	fi
-	if start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile "${PIDFILE}" --exec "${DAEMON}" -- $DAEMON_ARGS ; then
-	    log_end_msg 0
-	else
-	    log_end_msg 1
-	fi
+status)
+	status_of_proc
 	;;
-
-  status)
-	if init_is_upstart; then
-	    exit 1
-	fi
-	status_of_proc -p "${PIDFILE}" "${DAEMON}" "c8y-log-plugin" && exit 0 || exit $?
+restart)
+	# Always start the service regardless the status of do_stop
+	do_stop
+	do_start
 	;;
-
-  *)
-	log_action_msg "Usage: /etc/init.d/c8y-log-plugin {start|stop|restart|status}"
-	exit 1
+try-restart|force-reload)
+	# force-reload is the same as reload or try-restart according
+	# to its definition, the reload is not implemented here, so
+	# force-reload is the alias of try-restart here, but it should
+	# be the alias of reload if reload is implemented.
+	#
+	# Only start the service when do_stop succeeds
+	do_stop && do_start
+	;;
+#reload)
+	# If the "reload" action is implemented properly, then let the
+	# force-reload be the alias of reload, and remove it from
+	# try-restart|force-reload)
+	#
+	#do_reload
+	#;;
+*)
+	echo "Usage: $0 {start|stop|status|restart|try-restart|force-reload}" >&2
+	exit 3
+	;;
 esac
-
-exit 0
